### ISSUE TITLE
Refactor HappyHTTP to use net:URLFetcher

### ISSUE THREAD

**Issue by tmancey** [brave-intl/bat-native-confirmations#10]
**Subtasks:**

- [x] Refactor `HappyHTTP` to use `net::URLFetcher`
- [x] Refactor net::URLFetcher calls to be synchronous
- [x] URLRequests should retry if not successful
