### ISSUE TITLE
Implement timers

### ISSUE THREAD

**Issue by tmancey** [brave-intl/bat-native-confirmations#28]
**Subtasks:**

- [x] Implement `OnTimer` as a proxy to bat-native-ledger `OnTimer`
- [x] Refactor to use `OnTimer` to trigger events based up on spec
- [x] Implement `SetTimer` as a proxy to bat-native-ledger `SetTimer`
- [x] Refactor to use `SetTimer` to schedule events based up on spec
- [x] Implement `KillTimer` as a proxy to bat-native-ledger `KillTimer`
- [x] Refactor to use `KillTimer` to unschedule events based up on spec
