### ISSUE TITLE
Persist and reset Confirmations state

### ISSUE THREAD

**Issue by tmancey** [brave-intl/bat-native-confirmations#30]
**Subtasks:**

- [x] Implement `Save` as a proxy to bat-native-ledger `Save`
- [x] Implement `Load` as a proxy to bat-native-ledger `Load`
- [x] Implement `Reset` as a proxy to bat-native-ledger `Reset`
